version: "3"
services:
  wheelzloop_backend:
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - wheelzloop_backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network
networks:
  node_network:
