version: "3"
services:
  wheelzloop_backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
    env_file:
      - .env
