name: CI/CD Pipeline for Wheelzloop

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: npm install

      # - name: Run Backend Tests
      #   run: npm test

      - name: Run Unit Tests
        run: npm run test:unit

      # - name: Run Integration Tests
      #   run: npm run test:integration

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
